# Generated by Django 5.2.1 on 2026-01-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='nomi_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='nomi_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='nomi_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
    ]
